/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul7;

import javax.swing.JOptionPane;

/**
 *
 * @author Prdigma
 */
public class modul7_3 extends javax.swing.JFrame {

    /**
     * Creates new form modul7_3
     */
    public modul7_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSisiKubus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BtnKubus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jJariBola = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BtnBola = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanjangBalok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLebarBalok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTinggiBalok = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BtnBalok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 10, 270, 40);

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Vani", 0, 12)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(70, 20, 180, 40);
        jPanel2.add(jSisiKubus);
        jSisiKubus.setBounds(60, 60, 150, 40);

        jLabel9.setFont(new java.awt.Font("Vani", 0, 12)); // NOI18N
        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(220, 70, 40, 20);

        BtnKubus.setFont(new java.awt.Font("Vani", 0, 12)); // NOI18N
        BtnKubus.setText("Volume");
        BtnKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKubusActionPerformed(evt);
            }
        });
        jPanel2.add(BtnKubus);
        BtnKubus.setBounds(80, 120, 120, 40);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        jLabel10.setText("Masukkan Panjang Jari-jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(60, 20, 190, 40);
        jPanel3.add(jJariBola);
        jJariBola.setBounds(70, 60, 150, 30);

        jLabel11.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(240, 70, 40, 20);

        BtnBola.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        BtnBola.setText("Volume");
        BtnBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBolaActionPerformed(evt);
            }
        });
        jPanel3.add(BtnBola);
        BtnBola.setBounds(120, 120, 80, 40);

        jTabbedPane1.addTab("Bola", jPanel3);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel2.setText("Masukkan Panjang :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 20, 100, 30);
        jPanel1.add(jPanjangBalok);
        jPanjangBalok.setBounds(120, 20, 160, 30);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel3.setText("cm");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 20, 30, 20);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel4.setText("cm");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 70, 30, 20);
        jPanel1.add(jLebarBalok);
        jLebarBalok.setBounds(120, 70, 160, 30);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel5.setText("Masukkan Lebar    :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 70, 100, 30);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 130, 30, 20);
        jPanel1.add(jTinggiBalok);
        jTinggiBalok.setBounds(120, 120, 160, 30);

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel7.setText("Masukkan Panjang :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 120, 100, 30);

        BtnBalok.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        BtnBalok.setText("Hitung");
        BtnBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBalokActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBalok);
        BtnBalok.setBounds(150, 180, 90, 30);

        jTabbedPane1.addTab("Balok", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 40, 380, 250);

        setBounds(0, 0, 418, 349);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBalokActionPerformed
        int panjang,lebar,tinggi;
        panjang=Integer.parseInt(jPanjangBalok.getText());
        lebar=Integer.parseInt(jLebarBalok.getText());
        tinggi=Integer.parseInt(jTinggiBalok.getText());
        
        int hasil=panjang*lebar*tinggi;
        try {
            JOptionPane.showMessageDialog(null, "Volume Balok Adalah :"+hasil, "luas",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e, "Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBalokActionPerformed

    private void BtnKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKubusActionPerformed
        int sisi;
        sisi=Integer.parseInt(jSisiKubus.getText());
        
        int hasil=sisi*sisi*sisi;
        try {
            JOptionPane.showMessageDialog(null, "Volume Kubus Adalah :"+hasil, "luas",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e, "Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKubusActionPerformed

    private void BtnBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBolaActionPerformed
        float jari;
        jari=Integer.parseInt(jJariBola.getText());
        
        float hasil=(float)(4/3*3.14*jari*jari*jari);
        try {
            JOptionPane.showMessageDialog(null, "Luas Permukaan Bola Adalah :"+hasil, "luas",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e, "Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul7_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul7_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul7_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul7_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul7_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBalok;
    private javax.swing.JButton BtnBola;
    private javax.swing.JButton BtnKubus;
    private javax.swing.JTextField jJariBola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLebarBalok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jPanjangBalok;
    private javax.swing.JTextField jSisiKubus;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTinggiBalok;
    // End of variables declaration//GEN-END:variables
}
